name: terra
version: 1-release
main: gg.scenarios.terra.Terra
commands:
  setmatch:
  uhc:
  config:
  whitelist:
    aliases: [wl]
  helpop:
  rhelpop:
  team:
  scenarios:
    aliases: [scen, explain]
  heal: